/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/app/dashboard/**/*.{js,jsx}',
    './src/componants/admin/**/*.{js,jsx}',
    // Public homepage is fully Tailwind. Its tailwind.css is imported from
    // src/app/page.js only, so utilities never load on the Bootstrap pages
    // and the .border/.shadow/.container class collisions stay contained.
    './src/app/page.js',
    './src/app/componants/siteHeader.js',
    './src/app/componants/siteFooter.js',
    './src/app/componants/exploreJobs.js',
    './src/app/componants/jobsCards.js',
    './src/app/componants/jobCard.js',
    './src/app/componants/jobCardSkeleton.js',
    './src/app/componants/blogCardSkeleton.js',
    './src/app/componants/skeleton.js',
    './src/app/componants/breadcrumb.js',
    './src/app/componants/jobsExplorer.js',
    './src/app/aboutus/page.js',
    './src/app/componants/faq.js',
    './src/app/componants/badge.js',
    './src/app/componants/button.js',
    './src/app/componants/card.js',
    './src/app/componants/container.js',
    './src/app/componants/sectionHeading.js',
    './src/app/componants/stateMessage.js',
    './src/app/componants/blogCard.js',
    './src/app/componants/featuredBlogCard.js',
    './src/app/componants/blogsExplorer.js',
    './src/app/componants/blogDetail.js',
    './src/app/componants/contactExplorer.js',
    './src/app/componants/jobDetail.js',
    './src/app/blogs/page.js',
    './src/app/blogs/[id]/page.js',
    './src/app/contactus/page.js',
    './src/app/jobs/page.js',
    './src/app/jobs/[id]/page.js',
  ],
  corePlugins: {
    // The public site relies on Bootstrap's base styles; Tailwind's reset
    // would otherwise clobber them since dashboard pages share the root layout.
    preflight: false,
    // Bootstrap already ships a .container; don't let Tailwind redefine it.
    container: false,
  },
  theme: {
    extend: {
      colors: {
        "cyan-bright": "#0EA5E9",
        "primary-fixed-dim": "#93ccff",
        "tertiary": "#a000b2",
        "on-primary": "#ffffff",
        "on-surface": "#0b1c30",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#c128d4",
        "berry-accent": "#D946EF",
        "inverse-primary": "#93ccff",
        "error": "#ba1a1a",
        "on-background": "#0b1c30",
        "surface-container-high": "#dce9ff",
        "on-error": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "surface-container-low": "#eff4ff",
        "background": "#f8f9ff",
        "on-secondary-fixed": "#131b2e",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "surface-tint": "#006398",
        "tertiary-fixed-dim": "#fda9ff",
        "primary-fixed": "#cce5ff",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "secondary-container": "#dae2fd",
        "status-warning": "#F59E0B",
        "navy-surface": "#0F172A",
        "surface-container": "#e5eeff",
        "navy-deep": "#0B132B",
        "outline-variant": "#bfc7d2",
        "on-error-container": "#93000a",
        "primary-container": "#007bb9",
        "surface-bright": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "secondary-fixed-dim": "#bec6e0",
        "outline": "#707881",
        "secondary": "#565e74",
        "on-secondary-container": "#5c647a",
        "surface": "#f8f9ff",
        "berry-deep": "#C026D3",
        "tertiary-fixed": "#ffd6fb",
        "on-primary-fixed-variant": "#004b73",
        "on-tertiary-fixed-variant": "#7d008c",
        "surface-card": "#FFFFFF",
        "on-surface-variant": "#3f4850",
        "teal-clinical": "#0D9488",
        "verified-green": "#10B981",
        "surface-variant": "#d3e4fe",
        "border-subtle": "#E2E8F0",
        "on-primary-fixed": "#001d31",
        "error-container": "#ffdad6",
        "primary": "#006194",
        "inverse-surface": "#213145",
        "secondary-fixed": "#dae2fd",
        "on-primary-container": "#fdfcff",
        "on-tertiary-fixed": "#36003d",
        "surface-crisp": "#F8FAFC",
        "on-secondary-fixed-variant": "#3f465c",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "space-md": "1rem",
        "space-sm": "0.75rem",
        "space-3xl": "4rem",
        "gutter-desktop": "1.5rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-xs": "0.5rem",
        "gutter-mobile": "1rem",
        "space-2xs": "0.25rem",
      },
      maxWidth: {
        // Single source of truth for the site's content width — use
        // `max-w-container` (via the <Container> component) instead of
        // repeating the literal `max-w-[1600px]` per section.
        container: "1600px",
      },
      fontFamily: {
        sans: ["var(--font-jakarta)", "sans-serif"],
      },
    },
  },
  plugins: [],
};
